# https://github.com/samuelmeuli/action-electron-builder
name: Run audit checks

on:
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Refresh
        run: |
          sudo apt-get update

      - name: Setup dependencies
        run: |
          sudo apt-get install -y libusb-1.0-0-dev libudev-dev

      - name: Install deps with big timeout
        run: |
          yarn install --network-timeout 600000

      - name: Audit dependencies
        #  1 for INFO
        #  2 for LOW
        #  4 for MODERATE
        #  8 for HIGH
        #  16 for CRITICAL
        # Only high and critical vulnerabilities should be accounted for
        # https://github.com/yarnpkg/yarn/issues/7260
        run: |
          /bin/bash -c 'yarn audit --level high; [[ $? -ge 8 ]] && exit 1 || exit 0'
