name: Build Linux Executable

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: node_modules
          key: ${{ runner.os }}-node12-${{ hashFiles('**/package-lock.json') }}

      - name: Install deps and tools
        run: |
          npm install -g yarn
          yarn install
          sudo apt-get install --no-install-recommends -y libopenjp2-tools
          sudo apt-get install --no-install-recommends -y rpm
          sudo apt-get install --no-install-recommends -y bsdtar

      - name: Build Executable Target (Linux)
        run: |
          yarn electron:build
